ALTER TABLE class_image
  ADD COLUMN IF NOT EXISTS face_detected_count INT DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS emotion_recognized_count INT DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS annotated_image_url VARCHAR(1000) DEFAULT NULL;

ALTER TABLE face_record
  ADD COLUMN IF NOT EXISTS error_message VARCHAR(500) DEFAULT NULL;
